<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_5831904b472f5',
		'title' => 'roadbook',
		'fields' => array (
			array (
				'key' => 'field_5831e2204573d',
				'label' => 'Reference',
				'name' => 'trip_id',
				'type' => 'number',
				'instructions' => 'Reference unique du séjour',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5833eb91dc2b1',
				'label' => 'Statut',
				'name' => 'status',
				'type' => 'select',
				'instructions' => 'Statut général de l\'event',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					0 => 'Crée',
					1 => 'Validé',
					2 => 'Refusé',
					3 => 'Validé Vendeur',
					4 => 'Validé Vendeur & manager',
					5 => 'Validé Vendeur & manager & client',
					6 => 'Activité non effectué (problème..)',
					7 => 'Activité effectué',
					8 => 'Archivé',
				),
				'default_value' => array (
					0 => 0,
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array (
				'key' => 'field_5831ee209af48',
				'label' => 'participants',
				'name' => 'participants',
				'type' => 'number',
				'instructions' => 'Nombre de participants prévus',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 1,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'personne(s)',
				'min' => 1,
				'max' => 9999,
				'step' => 1,
			),
			array (
				'key' => 'field_5831ee79f59b6',
				'label' => 'manager',
				'name' => 'manager',
				'type' => 'user',
				'instructions' => 'Le manager du projet',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'role' => array (
					0 => 'onlyoo_team',
					1 => 'shop_manager',
					2 => 'administrator',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5831eea1f59b7',
				'label' => 'Lieu',
				'name' => 'lieu',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'lieu',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'add_term' => 1,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5831eeb0f59b8',
				'label' => 'Theme',
				'name' => 'theme',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'theme',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'add_term' => 1,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_58319053c4a35',
				'label' => 'Activités',
				'name' => 'day',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_583190c3c4a38',
				'min' => '',
				'max' => '',
				'layout' => 'block',
				'button_label' => 'Ajouter un jour',
				'sub_fields' => array (
					array (
						'key' => 'field_583190c3c4a38',
						'label' => 'Date',
						'name' => 'daytime',
						'type' => 'date_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'd/m/Y',
						'return_format' => 'd/m/Y',
						'first_day' => 1,
					),
					array (
						'key' => 'field_583190e9c4a39',
						'label' => 'Activités',
						'name' => 'products',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => 'field_583190f9c4a3a',
						'min' => '',
						'max' => '',
						'layout' => 'block',
						'button_label' => 'Ajouter une activité',
						'sub_fields' => array (
							array (
								'key' => 'field_583190f9c4a3a',
								'label' => 'Activité',
								'name' => 'id',
								'type' => 'post_object',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'post_type' => array (
									0 => 'product',
								),
								'taxonomy' => array (
								),
								'allow_null' => 0,
								'multiple' => 0,
								'return_format' => 'id',
								'ui' => 1,
							),
							array (
								'key' => 'field_5831914dc4a3b',
								'label' => 'Heure',
								'name' => 'time',
								'type' => 'time_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'display_format' => 'H:i:s',
								'return_format' => 'H:i:s',
							),
							array (
								'key' => 'field_58319191c4a3c',
								'label' => 'Reference',
								'name' => 'uuid',
								'type' => 'number',
								'instructions' => 'Identifiant unique',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array (
								'key' => 'field_58319198c4a3d',
								'label' => 'Prix',
								'name' => 'price',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => 'euros',
								'min' => 0,
								'max' => 99999999,
								'step' => '',
							),
							array (
								'key' => 'field_583191a6c4a3e',
								'label' => 'validation',
								'name' => 'validation',
								'type' => 'checkbox',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									0 => 'Client',
									1 => 'Vendeur',
									2 => 'Project manager',
								),
								'default_value' => array (
								),
								'layout' => 'horizontal',
								'toggle' => 0,
								'return_format' => 'value',
							),
							array (
								'key' => 'field_5834cd36cad8c',
								'label' => 'participants',
								'name' => 'participants',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 1,
								'placeholder' => '',
								'prepend' => '',
								'append' => 'personne(s)',
								'min' => 1,
								'max' => 999,
								'step' => 1,
							),
						),
					),
				),
			),
			array (
				'key' => 'field_5831eef7f59b9',
				'label' => 'Budget minimum',
				'name' => 'budget_min',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'Euros',
				'min' => 0,
				'max' => 9999,
				'step' => '',
			),
			array (
				'key' => 'field_5831ef66f59ba',
				'label' => 'Budget maximum',
				'name' => 'budget_max',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'Euros',
				'min' => 0,
				'max' => 9999,
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'private_roadbook',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;